# ESTÁGIO 1: Build (Compilação)
FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
WORKDIR /build

# Copia o pom.xml do parent e o do gateway para baixar dependências
COPY pom.xml ./
COPY api-gateway/pom.xml api-gateway/
COPY auth-service/pom.xml auth-service/
COPY catalog-service/pom.xml catalog-service/

# Baixa as dependências do gateway
RUN mvn dependency:go-offline -pl api-gateway -am

# Copia o código fonte e compila
COPY api-gateway/src/ api-gateway/src/
RUN mvn clean package -DskipTests -pl api-gateway

# ESTÁGIO 2: Run (Execução)
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Cria um usuário não-root para segurança
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Copia apenas o .jar gerado no estágio 1
COPY --from=builder /build/api-gateway/target/*.jar app.jar

# Expõe a porta (A porta real será sobrescrita no docker-compose)
EXPOSE 8080

# Ponto de entrada otimizado para containers
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]
