spring:
  application:
    name: auth-service
  profiles:
    active: local
server:
  port: ${AUTH_SERVICE_PORT:8081}
rsa:
  private:
    key: ${RSA_PRIVATE_KEY_VALUE:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
