syntax = "proto3";

package br.com.beauty.catalog.grpc;

option java_multiple_files = true;
option java_package = "br.com.beauty.catalog.grpc";
option java_outer_classname = "CatalogProto";

service CatalogGrpcService {
  // Retorna a grade de horários e os detalhes do serviço para o cálculo do Booking
  rpc GetProfessionalSchedule (ScheduleRequest) returns (ScheduleResponse);
}

message ScheduleRequest {
  string establishment_id = 1;
  string professional_id = 2;
  string service_id = 3;
}

message ScheduleResponse {
  bool is_active = 1;
  double price = 2;
  int32 duration_minutes = 3;
  repeated DaySchedule fixed_schedule = 4;
}

message DaySchedule {
  int32 day_of_week = 1; // 1 (Segunda) a 7 (Domingo)
  string start_time = 2; // "09:00"
  string end_time = 3;   // "18:00"
}
