spring:
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

catalog:
  service:
    uri: ${CATALOG_SERVICE_URI:http://catalog-service:8083}
