spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/${MONGO_DB:review_db}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8084

app:
  openapi:
    server-url: ${OPENAPI_SERVER_URL:http://localhost:8080/api/reviews}
